apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service_2
  description: "Сервис 2."
spec:
  type: service
  lifecycle: production
  owner: team-name
  dependsOn:
    - component:back_2
